[package]
name = "stream-patterns"
version = "0.2.1"
edition = "2021"

[dependencies]
async-channel = "1.9.0"
futures-util = { version = "0.3.29", features = [
    "sink",
    "std",
], default-features = false }

[dev-dependencies]
futures-channel = "0.3.29"
