[package]
name = "stream-patterns"
version = "0.1.1"
edition = "2021"

[dependencies]
async-channel = "1.9.0"
futures-io = "0.3.29"
futures-util = { version = "0.3.29", features = ["sink"] }

[dev-dependencies]
futures-channel = "0.3.29"
